<!DOCTYPE html>
<html>

<head>
    <style>
        body {
            font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif;
            color: #333;
            line-height: 1.6;
        }

        .container {
            max-width: 600px;
            margin: 0 auto;
            padding: 20px;
            border: 1px solid #e2e8f0;
            border-radius: 8px;
        }

        .header {
            background-color: #1e3c72;
            color: white;
            padding: 15px 20px;
            border-radius: 8px 8px 0 0;
            margin-bottom: 20px;
        }

        .details {
            background-color: #f8fafc;
            padding: 15px;
            border-radius: 6px;
            margin-bottom: 20px;
            border: 1px solid #e2e8f0;
        }

        .label {
            font-weight: bold;
            color: #64748b;
            font-size: 0.9em;
            text-transform: uppercase;
        }

        .message-box {
            padding: 15px;
            border-left: 4px solid #1e3c72;
            background-color: #f1f5f9;
        }
    </style>
</head>

<body>
    <div class="container">
        <div class="header">
            <h2 style="margin: 0;">New System Support Request</h2>
        </div>

        <p>A new issue has been reported by a user in the Smart Attendance System.</p>

        <div class="details">
            <table width="100%">
                <tr>
                    <td width="30%" class="label">Reporter Name:</td>
                    <td>{{ $ticketData['name'] }}</td>
                </tr>
                <tr>
                    <td class="label">Email:</td>
                    <td>{{ $ticketData['email'] }}</td>
                </tr>
                <tr>
                    <td class="label">User Role:</td>
                    <td style="text-transform: capitalize;">{{ $ticketData['role'] }}</td>
                </tr>
                <tr>
                    <td class="label">Submitted At:</td>
                    <td>{{ $ticketData['time'] }}</td>
                </tr>
            </table>
        </div>

        <p class="label">Issue Description:</p>
        <div class="message-box">
            {{ $ticketData['description'] }}
        </div>

        <p style="margin-top: 30px; font-size: 0.8em; color: #94a3b8;">
            This is an automated message generated by the Smart Attendance System. Please do not reply directly to this
            email. Instead, contact the user at their provided email address.
        </p>
    </div>
</body>

</html>
